### ISSUE TITLE
Files not found

### ISSUE THREAD

**Issue by maringos** [jotech/gapseq#32] opened 2020-03-02 08:02 UTC
Hi,
I would like to inform you about the following errors:
```
stat: cannot stat ‘/home/***/software/gapseq/src/../dat/seq/Bacteria/rev/sequences.tar.gz’: No such file or directory
stat: cannot stat ‘/home/***/software/gapseq/src/../dat/seq/Bacteria/unrev/sequences.tar.gz’: No such file or directory
stat: cannot stat ‘/home/***/software/gapseq/src/../dat/seq/Bacteria/rxn/sequences.tar.gz’: No such file or directory
```
*** stands for my account name
I went through this path in the repository and indeed there are no such files.
Kind Regards,
Georgios

**Comment by jotech** [comment] 2020-03-03 16:22
The files are usually downloaded when they do not exist. Can't reproduce the error, what exactly did you do?

**Comment by maringos** [comment] 2020-03-04 08:43
I just run the command `/home/sukem109/software/gapseq/gapseq doall /home/sukem109/software/gapseq/toy/myb71.fna.gz`
[testgapseq.err.txt](https://github.com/jotech/gapseq/files/4286213/testgapseq.err.txt)

**Comment by jotech** [comment] 2020-03-04 09:13
what is the output if you run ``./src/update_sequences.sh`` manually and does the error reproduce afterwards?

**Comment by maringos** [comment] 2020-03-08 19:23
Hi,
I run the above command and fixed the errors as shown in the error file. Now it returns:
```
slurmstepd: error: _is_a_lwp: open() /proc/21577/status failed: No such file or directory
slurmstepd: error: _is_a_lwp: open() /proc/19803/status failed: No such file or directory
index file myb71.fna.tmp.fai not found, generating...
I think it seems ok, isn't?
```

**Comment by Waschina** [comment] 2020-03-26 12:23
Hi,
i also get this slurmstepd error. I'm looking into it...

**Comment by Waschina** [comment] 2020-03-26 13:48
okay,
I found this:

> Possible causes/remedies:
> 
> _is_a_lwp is a function called internally for Slurm job accounting. The message indicates a rare error situation with a function call. But the error shouldn't affect anything in the user job. Please ignore the message.
(https://docs.nersc.gov/jobs/jobs-faq/)

Even though, this issue isn't echnically closed, I will close it here since it seems that it does not directly stem from gapseq and since it seems not to affect gapseq outcomes.

**Closed** 2020-03-26 13:49 UTC
