### ISSUE TITLE
Question: GapSeq includes a protein as being present when it got a bad blast? 

### ISSUE THREAD

**Issue by Calvin2077** [jotech/gapseq#198] opened 2023-11-09 17:23 UTC
Good day,

My name is Calvin, and my overall question is, why did GapSeq include/accept a protein as being present when it got a bad blast? 

In more detail, I am using GapSeq to assess the metabolic pathways for a large group of Archaea. One group of pathways we are particularly interested in are Polyamines.

So I ran GapSeq using a bit-score of 60 and -z 2 (unreviewed only if reviewed not available), which all went well with no issues.

But, when I checked my results, "Putrescine Biosynthesis I" stood out as being complete in my species, which is strange as previous analysis (blast and KEGG) showed that my species lacked the "arginine decarboxylase" to make it happen.

Therefore, I checked the Reaction file (output from GapSeq), and I found that for all three examples of "arginine decarboxylase," they were labelled as "bad_blast" (which, according to the GapSeq wiki says it was due to blast hit with lower quality, i.e. lower bit-score, coverage, or identity than needed for cutoffs) 

All three had e-values = 5.82e-24 bit-scores = 86.3

Therefore, my question is, why did GapSeq include/accept "arginine decarboxylase" as being present when I got a bad blast? 

Is it due to the bit-score being higher than my threshold? However, oddly, when I checked another protein with a "bad blast" that got a similar value (e-value = 5.40e-21; bit-score = 89.7), the Pathway file said it was absent.

Any help would be much appreciated. Thanks 

Calvin

**Comment by Waschina** [comment] 2023-11-09 17:59
Hi Calvin,

I guess the reaction is added during the gap-filling. There, reactions with "blad_blast" might be added if they complete a metabolic functionality, e.g. a pathway to use a specific compound as an energy source. By default, gapseq considers reactions with a bitscore > 50 for those gap fillings. 

You can make the gap-filling step more strict by using the option "-b". E.g.
```sh
gapseq fill -m <genomeID>-draft.RDS -n <genomeID>-medium.csv -c <genomeID>-rxnWeights.RDS -g <genomeID>-rxnXgenes.RDS -b 100
```

This will reset the bitscore threshold during gap-filling to 100 instead of 50.

I hope this helps. 
Silvio

**Comment by Calvin2077** [comment] 2023-11-09 19:04
Hello Silvio,

Thank you very much for getting back to me so fast as it is much appreciated and means a lot so thank you. Also thank you for your help in my question!

However one thing I accidentally forgot to include in my question is I only ran "Gap-seq find" and I did not run gapseq fill or any other downstream steps.

Thanks and sorry for the confusion

**Comment by Waschina** [comment] 2023-11-09 19:26
I see. Could you perhaps share the part of the table "...-all-Reactions.tbl" with the said reaction? Ideally all rows for the pathway, which contains the reaction.

**Comment by Calvin2077** [comment] 2023-11-09 19:35
Of course here you go!

<img width="1350" alt="Screenshot 2023-11-09 at 2 35 17 PM" src="https://github.com/jotech/gapseq/assets/72618537/db926650-92a2-4ec9-ad9a-f8c54b31b432">

**Comment by Calvin2077** [comment] 2023-11-09 19:37
Also here is a screen shot showing that the pathway is complete
 
<img width="732" alt="Screenshot 2023-11-09 at 2 37 10 PM" src="https://github.com/jotech/gapseq/assets/72618537/eee8e8ce-3534-46f3-9423-c8e03278f08d">

**Comment by jotech** [comment] 2023-11-10 09:51
Thank you for reporting this issue! Can you please also post the output of 
```
./gapseq find -p PWY-40 -b 60 -z 2 your.genome.fna
```

**Comment by Calvin2077** [comment] 2023-11-10 14:32
You're welcome and thank you for your help and assistance it is much appreciated and of course!
<img width="1192" alt="Screenshot 2023-11-10 at 9 31 35 AM" src="https://github.com/jotech/gapseq/assets/72618537/ccf79486-6c99-46c2-a133-e419adc11118">

**Comment by jotech** [comment] 2023-11-10 15:57
okay, thank you! That the relations are found makes sense since you lowered the bitscore. However, it is still unclear why it is labeled as a "bad blast" hit.

**Comment by Calvin2077** [comment] 2023-11-10 19:28
Okay so the problem lies in lowering the bit-score this does make sense so thank you. However, when I checked another protein/enzyme that has a bit-score of 89.7 the output of GapSeq says it is absent. Please see attached photo
<img width="1045" alt="Screenshot 2023-11-10 at 2 27 37 PM" src="https://github.com/jotech/gapseq/assets/72618537/6208596e-ee91-4d57-b069-30b9b0a3401d">

**Comment by Waschina** [comment] 2023-11-11 17:42
Hi Calvin,

I tried to reproduce the issue with an [Nitrosothermus koennekii](https://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/003/695/185/GCA_003695185.1_ASM369518v1/) assembly from NCBI. Everything was just as expected: There were no bad_blast hits for Pathway PWY-40.

Could you run the following commands and post the output?

```sh
gapseq find -p PWY-40 -t Archaea -b 60 Nitrosothermus_koennekii.faa
cat Nitrosothermus_koennekii-PWY-40-Reactions.tbl
cat Nitrosothermus-PWY-40-Pathways.tbl
```

**Comment by Calvin2077** [comment] 2023-11-11 19:18
Hello!

Thank you for reproducing my data/.faa to try and find the source of the error. It is much appreciated!

As requested here are the photos of my output (.tsv instead of cat for more clarity for me) and like yourself I am getting no "bad_blast" for PWY-40. Which is incredible strange and odd I have likewise tried running GapSeq on the entire "Polyamine-Biosynthesis" and am still getting now a "good_blast" (in other words no "bad_blast")

Very odd but seems like in the end I think the major source of the problem (in why this protein was included when other analysis didn't) might be related to the low bit-score I set up.    

I tried to reproduce the issue with an [Nitrosothermus koennekii](https://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/003/695/185/GCA_003695185.1_ASM369518v1/) assembly from NCBI. Everything was just as expected: There were no bad_blast hits for Pathway PWY-40.

Could you run the following commands and post the output?

<img width="1133" alt="Screenshot 2023-11-11 at 1 52 15 PM" src="https://github.com/jotech/gapseq/assets/72618537/d9d1238b-401b-4d1b-a1bd-5739b1768bd0">
<img width="662" alt="Screenshot 2023-11-11 at 1 50 42 PM" src="https://github.com/jotech/gapseq/assets/72618537/332e2dcf-4302-48d9-9529-915e2f8a63c6">
<img width="1140" alt="Screenshot 2023-11-11 at 1 50 28 PM" src="https://github.com/jotech/gapseq/assets/72618537/0de443cf-12e9-4819-ad1a-31696f2b1f26">

**Comment by Calvin2077** [comment] 2023-11-11 19:25
However, if it is okay, I just have another confusing find in that ORNDECARBOX-RXN ornithine decarboxylase 4.1.1.17 (please see the attached photos) says it is has a "bad_blast" yet the bit-score is above my 60 threshold (bit-score 86.9), whereas the output says ARGINASE-RXN (arginase) is present.

One idea, I am thinking it is related to ORNDECARBOX-RXN ornithine decarboxylase having "bihit" as NA while  ARGINASE-RXN (arginase) doesn't. Therefore do you think this the reason? If so, and I apologize (as I am still pretty new to bioinfomatics) but what does "bihit" {Bidirectional hit} mean?

Thanks again for all your help it is so very much appreciated! 
	
<img width="1205" alt="Screenshot 2023-11-11 at 2 11 57 PM" src="https://github.com/jotech/gapseq/assets/72618537/2aa4f047-ecb4-4524-8985-5e7798fb493e">
<img width="1117" alt="Screenshot 2023-11-11 at 2 12 43 PM" src="https://github.com/jotech/gapseq/assets/72618537/feb84da8-420e-44ca-b7e1-b353e444a6b8">

**Comment by Waschina** [comment] 2023-11-12 11:12
Hi Calvin, 

unfortunately, your screenshot does not show the entire table (That is why I suggested the output of the `cat` command). You will see that the column "exception" says 1 for EC 4.1.1.17. This means this enzyme requires a higher identity to be identified as "good_blast". The gapseq publication in the section "Pathway and subsystem prediction" explains the exception handling.

**Comment by Waschina** [comment] 2023-11-28 09:00
I am closing the issue for now as we can not reproduce the described problem. Please feel free to re-open if issue remains.

**Closed by Waschina** 2023-11-28 09:00 UTC
