### ISSUE TITLE
loss of model attributes when converting SBML to RDS causing error in gapfilling

### ISSUE THREAD

**Issue by estebano11** [jotech/gapseq#133] opened 2022-08-11 16:03 UTC
> for bug reports and errors please report the output of: ./gapseq test
Hi, 
Thank you for the software, I am finding it very useful. 
I added reactions in different compartments (extracellular, periplasm, etc)  in the sbml file (xml) because I find it easier working on python instead of R. But I wanted to know if I can convert this file into RDS to make use of the gapfilling process. 
Do you think this is feasible?

Thank you!

Esteban.

**Comment by jotech** [comment] 2022-08-15 08:40
hi, yes you can load xml files in R using the package sybilSBML
```R
library(sybilSBML)
readSBMLmod("my.xml")
```

**Comment by estebano11** [comment] 2022-08-15 10:14
Hi, thanks for the reply.

Sorry in my first comment didn't specify with details.
I have done this but I have an error when I want to use the RDS file with gapseq.
Doing with ecoli in toys:

```
gapseq fill -m ecoli-draft.RDS -n ecoli-medium.csv -g ecoli-rxnXgenes.RDS -c ecoli-rxnWeights.RDS
...
Final growth rate:     1.941537 

Uptake at limit:
Maltose:2.5, NH3:10, N-Acetyl-D-glucosamine:5, Neu5Ac:5, Melitose:1.67, Sucrose:2.5, O2:12.5 

Top 10 produced metabolites:
H+:50.658, Acetate:49.47, H2O:34.554, CO2:20.421, H2:2.635, EX cpd11416 c0:1.942, Galactose:1.67, 5-Methylthio-D-ribose:0.007 
Warning message:
Model file already exists and will be overwritten! 
Wrote file ecoli.xml
Patching file ecoli.xml ... done
```

Then I use ecoli.xml to read it and export in RDS (I am aware that gapseq generate the RDS, but just to demostrate in the case when I want to modify the xml and then use it to gapfill)

```
library(sybilSBML)
mod <- readSBMLmod("ecoli.xml")
> mod <- readSBMLmod("ecoli.xml")
reading SBML file ... OK
getting the model ... OK
creating S and parsing constraints ... OK
GPR mapping ... OK
cleaning up ... OK
validating object ... OK
> mod
model name:              
number of compartments  3 
                        c0 
                        e0 
                        p0 
number of reactions:    3035 
number of metabolites:  2451 
number of unique genes: 1252 
objective function:     +1 EX_cpd11416_c0 

saveRDS(mod, "ecoli2.RDS")
```

When I want to use ecoli2.RDS in gapseq I have the following error:

```
gapseq fill -m ecoli2.RDS -n ecoli-medium.csv -g ecoli-rxnXgenes.RDS -c ecoli-rxnWeights.RDS
Loading model files ecoli2.RDS 
Error in `[.data.frame`(mod.orig@mod_attr, , "annotation") : 
  selezionate colonne non definite
Calls: grepl -> [ -> [.data.frame
Esecuzione interrotta

```
gapseq version: 1.2 315f35d

I attach the files generated just in case. Do you know if I can solve this issue?

Thanks
[ecoli.zip](https://github.com/jotech/gapseq/files/9336553/ecoli.zip)
!

**Comment by jotech** [comment] 2022-08-19 14:27
Hi,
I see; thanks for the clarification!
The problem is some data loss from importing and exporting the model again. I just committed a quick fix for this, but we should also take care of the data loss in general.

**Comment by jotech** [comment] 2022-08-19 14:38
I adapted the issue name to make it clearer

**Comment by estebano11** [comment] 2022-08-22 12:31
Hi jotech,
Thank you for the reply. Now is clear why I can't do this. I modified my script to use it in R, so I add the reactions to the draft RDS file instead of the xml using addReact().
In this way now I can work, if you can find the solution to export RDS from xml would be useful also. 

Thanks!

Esteban.

**Closed** 2022-09-05 15:46 UTC
